name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Grant required permissions for semantic-release to push commits/tags and create release notes
permissions:
  contents: write # needed to push tags and update CHANGELOG
  issues: write # allow commenting on issues (release notes references)
  pull-requests: write # allow commenting on PRs

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  release:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout (full history for semantic-release)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release needs full git history & tags
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
