name: Release & Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create GitHub Release & Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Publish to npm
        if: success()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing version $(node -p "require('./package.json').version")"
          npm publish

      - name: Generate release notes from CHANGELOG
        id: notes
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          awk -v ver="$VERSION" '
            BEGIN{found=0}
            /^## [0-9]+\.[0-9]+\.[0-9]+ - / { if(found){exit} if($2==ver){found=1; next} }
            found { print }
          ' CHANGELOG.md | sed '/^## Unreleased/,$d' | sed '/^$/N;/^\n$/D' > RELEASE_NOTES.md
          echo "--- RELEASE NOTES ---"; cat RELEASE_NOTES.md
          echo "notes_file=RELEASE_NOTES.md" >> $GITHUB_OUTPUT

      - name: Create GitHub Release (from changelog)
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
